version: '3.8'

services:
  postgres_nlw:
    container_name: automacaoPython2
    image: postgres
    ports: 
      - "3334:3334"

  environment:     
    POSTGRES_USER=admin
    POSTGRES_PASSWORD=admin